spring:
  application:
    name: shiv-horse-service
  datasource:
    url: jdbc:sqlite:./data/horse.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
